### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by tsutsumi1105** [tsutsumi1105/grade_fes_unit_hub#26]
■Webアプリの概要
enza版対応ゲーム「アイドルマスターシャイニーカラーズ」のグレードフェスというコンテンツで使用している自分の編成を投稿、紹介できる掲示板サービス。
ユーザーは自分の編成の情報を画像と文章で投稿することができる。
ユーザーは他のユーザーの投稿記事を見ることができる。
ユーザーは記事に対してコメントをすることができる。
ユーザーは他の人の記事や自分の記事に対してのコメントを参考に自分の編成をさらに強化するためのヒントを得ることができる。
ユーザー同士の交流を生みだし、コミュニティを形成するきっかけを作る。

■1週間辺りの開発に向けられる時間
- 1週間あたり：20時間

（ストーリポイント1消費するのに2時間を目安として、1週間あたりどれだけストーリポイントを消化できるか確認してください）

■ProjectsのURL
https://github.com/users/tsutsumi1105/projects/1/views/1

■MVPリリースまで
- [x] 環境構築
- [x] デプロイ
- [x] ユーザー機能
- [x] ログイン
- [x] ログアウト
- [x] 記事の一覧
- [x] 記事の投稿
- [x] 記事の詳細
- [x] 記事の編集
- [x] 記事の削除
- [x] コメント機能
- [x] 検索機能
- [x] ヘッダー

■MVP後
- [x] いいね機能
- [x] ブックマーク機能
- [x] タグ機能
- [x] マイページ
- [x] ユーザー詳細
- [x] ユーザーフォロー機能
- [x] 下書き機能
- [x] SNS共有機能
- [x] 通知機能

■MVPレビュー依頼予定日
予定日：2024年 12月 28日

**Comment by kenchasonakai** [comment]
LGTMです！
